local_repository(
    name = "rules_proto_grpc",
    path = "../../../",
)

load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_toolchains", "rules_proto_grpc_dependencies")
rules_proto_grpc_toolchains()
rules_proto_grpc_dependencies()

load("@rules_proto_grpc//android:repositories.bzl", rules_proto_grpc_android_repos="android_repos")

rules_proto_grpc_android_repos()

load("@io_grpc_grpc_java//:repositories.bzl", "grpc_java_repositories")

grpc_java_repositories(
    omit_bazel_skylib = True,
    omit_com_google_protobuf = True,
    omit_com_google_protobuf_javalite = True,
    omit_net_zlib = True,
)
