bazel_dep(name = "protobuf", version = "35.1")
bazel_dep(name = "rules_java", version = "9.3.0")
bazel_dep(name = "rules_jvm_external", version = "6.10")
bazel_dep(name = "rules_proto_grpc_java", version = "0.0.0.rpg.version.placeholder")

local_path_override(
    module_name = "rules_proto_grpc",
    path = "../../modules/core",
)

local_path_override(
    module_name = "rules_proto_grpc_java",
    path = "../../modules/java",
)

# Load a different version of protobuf into this workspace's 'maven' repo. The Java rules use their
# own private Maven hub, so this test verifies that callers still get a single protobuf runtime on
# the classpath.
maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    name = "java_deps_maven",
    artifacts = [
        "com.google.protobuf:protobuf-java:4.35.1",
        "com.google.protobuf:protobuf-java-util:4.35.1",
    ],
    known_contributing_modules = [
        # Supress warning about multiple contributing modules
        "",
        "protobuf",
        "rules_proto_grpc_java",
    ],
)
use_repo(maven, maven = "java_deps_maven")
