local_repository(
    name = "rules_proto_grpc",
    path = "../../../",
)

load("@rules_proto_grpc//d:deps.bzl", "d_deps")

d_deps()

load("@io_bazel_rules_d//d:d.bzl", "d_repositories")

d_repositories()
