local_repository(
    name = "rules_proto_grpc",
    path = "../../../../../",
)

load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_toolchains")
rules_proto_grpc_toolchains()

load("@rules_proto_grpc//github.com/stackb/grpc.js:repositories.bzl", rules_proto_grpc_grpcjs_repos="grpcjs_repos")

rules_proto_grpc_grpcjs_repos()

load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")

closure_repositories()
