local_repository(
    name = "rules_proto_grpc",
    path = "../../../../../",
)

load("@rules_proto_grpc//github.com/stackb/grpc.js:repositories.bzl", "grpcjs_deps")

grpcjs_deps()

load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")

closure_repositories()
