Contributions are very welcome on this project. Issues should be raised for bugs
and feature requests. Pull requests should be targeted at the master branch and
will run against CI.

Note: The rules in the repo are generated by the code in [tools/rulegen](/tools/rulegen)
and the output rules should therefore not be edited directly. However, if you are
not comfortable editing this code, please submit a PR with just the output files
edited and we'll help update the generator to get the desired result.

Please see the [Developers](https://github.com/rules-proto-grpc/rules_proto_grpc#developers)
section of the project README for further details on how these rules are structured.
