"""Generated nuget packages"""

load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "nuget_package")

# Backwards compatibility definitions
def nuget_protobuf_packages():
    nuget_rules_proto_grpc_packages()

def nuget_grpc_packages():
    nuget_rules_proto_grpc_packages()

def no_op():
    # Function that does nothing, to be placeholder in below function. This prevents it being a
    # syntax error when nuget2bazel is first run
    pass

def nuget_rules_proto_grpc_packages():
    """Nuget packages"""
    no_op()

    ### Generated by the tool
    nuget_package(
        name = "system.buffers",
        package = "system.buffers",
        version = "4.5.1",
        sha256 = "c30b3dd2c7e2f4cee4b823d692fd42118309b42ab1f5007f923d329a5b0d6b12",
    )
    nuget_package(
        name = "system.numerics.vectors",
        package = "system.numerics.vectors",
        version = "4.5.0",
        sha256 = "a9d49320581fda1b4f4be6212c68c01a22cdf228026099c20a8eabefcf90f9cf",
    )
    nuget_package(
        name = "system.runtime.compilerservices.unsafe",
        package = "system.runtime.compilerservices.unsafe",
        version = "4.7.1",
        sha256 = "52fca80d5f0ed286371cf1b519b039e9855dbf04c611f8d8479816d4eec82b85",
        core_lib = {
            "netcoreapp2.0": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp2.1": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp2.2": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp3.0": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp3.1": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "net5.0": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "net6.0": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
        },
        core_ref = {
            "netcoreapp2.0": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp2.1": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp2.2": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp3.0": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp3.1": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "net5.0": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "net6.0": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
        },
        core_files = {
            "netcoreapp2.0": [
                "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
                "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
            "netcoreapp2.1": [
                "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
                "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
            "netcoreapp2.2": [
                "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
                "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
            "netcoreapp3.0": [
                "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
                "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
            "netcoreapp3.1": [
                "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
                "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
            "net5.0": [
                "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
                "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
            "net6.0": [
                "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
                "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
        },
    )
    nuget_package(
        name = "system.memory",
        package = "system.memory",
        version = "4.5.5",
        sha256 = "10f43da352a29fb2b3188e4edd4dcf5100194c8b526e4f61fe2e2b5623775a22",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/System.Memory.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
                "@system.runtime.compilerservices.unsafe//:netcoreapp2.0_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
                "lib/netstandard2.0/System.Memory.dll",
                "lib/netstandard2.0/System.Memory.xml",
            ],
        },
    )
    nuget_package(
        name = "google.protobuf",
        package = "google.protobuf",
        version = "3.21.5",
        sha256 = "f94cf5d860aa9ad1042f255b3d9b6b041f649d8d6bed4e343c54f2dd8cf8f16f",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Google.Protobuf.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Google.Protobuf.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Google.Protobuf.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Google.Protobuf.dll",
            "netcoreapp3.1": "lib/netstandard2.0/Google.Protobuf.dll",
            "net5.0": "lib/net5.0/Google.Protobuf.dll",
            "net6.0": "lib/net5.0/Google.Protobuf.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
                "@system.memory//:netcoreapp2.0_core",
                "@system.runtime.compilerservices.unsafe//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
                "@system.memory//:netcoreapp2.1_core",
                "@system.runtime.compilerservices.unsafe//:netcoreapp2.1_core",
            ],
            "netcoreapp2.2": [
                "@system.memory//:netcoreapp2.2_core",
                "@system.runtime.compilerservices.unsafe//:netcoreapp2.2_core",
            ],
            "netcoreapp3.0": [
                "@system.memory//:netcoreapp3.0_core",
                "@system.runtime.compilerservices.unsafe//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
                "@system.memory//:netcoreapp3.1_core",
                "@system.runtime.compilerservices.unsafe//:netcoreapp3.1_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
                "lib/netstandard2.0/Google.Protobuf.dll",
                "lib/netstandard2.0/Google.Protobuf.pdb",
                "lib/netstandard2.0/Google.Protobuf.xml",
            ],
            "netcoreapp2.1": [
                "lib/netstandard2.0/Google.Protobuf.dll",
                "lib/netstandard2.0/Google.Protobuf.pdb",
                "lib/netstandard2.0/Google.Protobuf.xml",
            ],
            "netcoreapp2.2": [
                "lib/netstandard2.0/Google.Protobuf.dll",
                "lib/netstandard2.0/Google.Protobuf.pdb",
                "lib/netstandard2.0/Google.Protobuf.xml",
            ],
            "netcoreapp3.0": [
                "lib/netstandard2.0/Google.Protobuf.dll",
                "lib/netstandard2.0/Google.Protobuf.pdb",
                "lib/netstandard2.0/Google.Protobuf.xml",
            ],
            "netcoreapp3.1": [
                "lib/netstandard2.0/Google.Protobuf.dll",
                "lib/netstandard2.0/Google.Protobuf.pdb",
                "lib/netstandard2.0/Google.Protobuf.xml",
            ],
            "net5.0": [
                "lib/net5.0/Google.Protobuf.dll",
                "lib/net5.0/Google.Protobuf.pdb",
                "lib/net5.0/Google.Protobuf.xml",
            ],
            "net6.0": [
                "lib/net5.0/Google.Protobuf.dll",
                "lib/net5.0/Google.Protobuf.pdb",
                "lib/net5.0/Google.Protobuf.xml",
            ],
        },
    )
    nuget_package(
        name = "grpc.core.api",
        package = "grpc.core.api",
        version = "2.47.0",
        sha256 = "cce27d5afbbc5e23d289c2c494a2f2dce24b655709c4833759d46ee019f679cb",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Grpc.Core.Api.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Grpc.Core.Api.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Grpc.Core.Api.dll",
            "netcoreapp3.0": "lib/netstandard2.1/Grpc.Core.Api.dll",
            "netcoreapp3.1": "lib/netstandard2.1/Grpc.Core.Api.dll",
            "net5.0": "lib/netstandard2.1/Grpc.Core.Api.dll",
            "net6.0": "lib/netstandard2.1/Grpc.Core.Api.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
                "@system.memory//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
                "@system.memory//:netcoreapp2.1_core",
            ],
            "netcoreapp2.2": [
                "@system.memory//:netcoreapp2.2_core",
            ],
            "netcoreapp3.0": [
                "@system.memory//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
                "@system.memory//:netcoreapp3.1_core",
            ],
            "net5.0": [
                "@system.memory//:net5.0_core",
            ],
            "net6.0": [
                "@system.memory//:net6.0_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
                "lib/netstandard2.0/Grpc.Core.Api.dll",
                "lib/netstandard2.0/Grpc.Core.Api.pdb",
                "lib/netstandard2.0/Grpc.Core.Api.xml",
            ],
            "netcoreapp2.1": [
                "lib/netstandard2.0/Grpc.Core.Api.dll",
                "lib/netstandard2.0/Grpc.Core.Api.pdb",
                "lib/netstandard2.0/Grpc.Core.Api.xml",
            ],
            "netcoreapp2.2": [
                "lib/netstandard2.0/Grpc.Core.Api.dll",
                "lib/netstandard2.0/Grpc.Core.Api.pdb",
                "lib/netstandard2.0/Grpc.Core.Api.xml",
            ],
            "netcoreapp3.0": [
                "lib/netstandard2.1/Grpc.Core.Api.dll",
                "lib/netstandard2.1/Grpc.Core.Api.pdb",
                "lib/netstandard2.1/Grpc.Core.Api.xml",
            ],
            "netcoreapp3.1": [
                "lib/netstandard2.1/Grpc.Core.Api.dll",
                "lib/netstandard2.1/Grpc.Core.Api.pdb",
                "lib/netstandard2.1/Grpc.Core.Api.xml",
            ],
            "net5.0": [
                "lib/netstandard2.1/Grpc.Core.Api.dll",
                "lib/netstandard2.1/Grpc.Core.Api.pdb",
                "lib/netstandard2.1/Grpc.Core.Api.xml",
            ],
            "net6.0": [
                "lib/netstandard2.1/Grpc.Core.Api.dll",
                "lib/netstandard2.1/Grpc.Core.Api.pdb",
                "lib/netstandard2.1/Grpc.Core.Api.xml",
            ],
        },
    )
    nuget_package(
        name = "grpc.net.common",
        package = "grpc.net.common",
        version = "2.47.0",
        sha256 = "08f0ee4a023fba9c74ad27930ad7c66f5708164212a30551db8fc4742c3df012",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Grpc.Net.Common.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Grpc.Net.Common.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Grpc.Net.Common.dll",
            "netcoreapp3.0": "lib/netstandard2.1/Grpc.Net.Common.dll",
            "netcoreapp3.1": "lib/netstandard2.1/Grpc.Net.Common.dll",
            "net5.0": "lib/net5.0/Grpc.Net.Common.dll",
            "net6.0": "lib/net6.0/Grpc.Net.Common.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
                "@grpc.core.api//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
                "@grpc.core.api//:netcoreapp2.1_core",
            ],
            "netcoreapp2.2": [
                "@grpc.core.api//:netcoreapp2.2_core",
            ],
            "netcoreapp3.0": [
                "@grpc.core.api//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
                "@grpc.core.api//:netcoreapp3.1_core",
            ],
            "net5.0": [
                "@grpc.core.api//:net5.0_core",
            ],
            "net6.0": [
                "@grpc.core.api//:net6.0_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
                "lib/netstandard2.0/Grpc.Net.Common.dll",
                "lib/netstandard2.0/Grpc.Net.Common.pdb",
                "lib/netstandard2.0/Grpc.Net.Common.xml",
            ],
            "netcoreapp2.1": [
                "lib/netstandard2.0/Grpc.Net.Common.dll",
                "lib/netstandard2.0/Grpc.Net.Common.pdb",
                "lib/netstandard2.0/Grpc.Net.Common.xml",
            ],
            "netcoreapp2.2": [
                "lib/netstandard2.0/Grpc.Net.Common.dll",
                "lib/netstandard2.0/Grpc.Net.Common.pdb",
                "lib/netstandard2.0/Grpc.Net.Common.xml",
            ],
            "netcoreapp3.0": [
                "lib/netstandard2.1/Grpc.Net.Common.dll",
                "lib/netstandard2.1/Grpc.Net.Common.pdb",
                "lib/netstandard2.1/Grpc.Net.Common.xml",
            ],
            "netcoreapp3.1": [
                "lib/netstandard2.1/Grpc.Net.Common.dll",
                "lib/netstandard2.1/Grpc.Net.Common.pdb",
                "lib/netstandard2.1/Grpc.Net.Common.xml",
            ],
            "net5.0": [
                "lib/net5.0/Grpc.Net.Common.dll",
                "lib/net5.0/Grpc.Net.Common.pdb",
                "lib/net5.0/Grpc.Net.Common.xml",
            ],
            "net6.0": [
                "lib/net6.0/Grpc.Net.Common.dll",
                "lib/net6.0/Grpc.Net.Common.pdb",
                "lib/net6.0/Grpc.Net.Common.xml",
            ],
        },
    )
    ### End of generated by the tool
