local_repository(
    name = "rules_proto_grpc",
    path = "../../../",
)

load("@rules_proto_grpc//objc:repositories.bzl", rules_proto_grpc_objc_repos="objc_repos")

rules_proto_grpc_objc_repos()

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()
