"""Generated nuget packages"""

load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "nuget_package", "dotnet_nuget_new")

# Backwards compatibility definitions
def nuget_protobuf_packages():
    nuget_rules_proto_grpc_packages()

def nuget_grpc_packages():
    nuget_rules_proto_grpc_packages()

def no_op():
    # Function that does nothing, to be placeholder in below function. This prevents it being a
    # syntax error when nuget2bazel is first run
    pass

def nuget_rules_proto_grpc_packages():
    """Nuget packages"""
    no_op()

    ### Generated by the tool
    nuget_package(
        name = "system.buffers",
        package = "system.buffers",
        version = "4.5.1",
        sha256 = "c30b3dd2c7e2f4cee4b823d692fd42118309b42ab1f5007f923d329a5b0d6b12",
    )
    nuget_package(
        name = "system.numerics.vectors",
        package = "system.numerics.vectors",
        version = "4.5.0",
        sha256 = "a9d49320581fda1b4f4be6212c68c01a22cdf228026099c20a8eabefcf90f9cf",
    )
    nuget_package(
        name = "system.runtime.compilerservices.unsafe",
        package = "system.runtime.compilerservices.unsafe",
        version = "4.7.1",
        sha256 = "52fca80d5f0ed286371cf1b519b039e9855dbf04c611f8d8479816d4eec82b85",
        core_lib = {
            "netcoreapp2.0": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp2.1": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp2.2": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp3.0": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp3.1": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "net5.0": "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
        },
        core_ref = {
            "netcoreapp2.0": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp2.1": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp2.2": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp3.0": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "netcoreapp3.1": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
            "net5.0": "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll",
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
            "netcoreapp2.1": [
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
            "netcoreapp2.2": [
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
            "netcoreapp3.0": [
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
            "netcoreapp3.1": [
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
            "net5.0": [
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll",
               "lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.xml",
            ],
        },
    )
    nuget_package(
        name = "system.memory",
        package = "system.memory",
        version = "4.5.4",
        sha256 = "dec0847f33b8823e4260672d97d657411461c00ada3107ec7bbcb32a845eeb91",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/System.Memory.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
               "@system.runtime.compilerservices.unsafe//:netcoreapp2.0_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/System.Memory.dll",
               "lib/netstandard2.0/System.Memory.xml",
            ],
        },
    )
    nuget_package(
        name = "google.protobuf",
        package = "google.protobuf",
        version = "3.18.0",
        sha256 = "7f08d1f6ba43c687183ad52a4ce7c44b2f52562378d5e18de18d4bf90d7fae51",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Google.Protobuf.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Google.Protobuf.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Google.Protobuf.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Google.Protobuf.dll",
            "netcoreapp3.1": "lib/netstandard2.0/Google.Protobuf.dll",
            "net5.0": "lib/net5.0/Google.Protobuf.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
               "@system.memory//:netcoreapp2.0_core",
               "@system.runtime.compilerservices.unsafe//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
               "@system.memory//:netcoreapp2.1_core",
               "@system.runtime.compilerservices.unsafe//:netcoreapp2.1_core",
            ],
            "netcoreapp2.2": [
               "@system.memory//:netcoreapp2.2_core",
               "@system.runtime.compilerservices.unsafe//:netcoreapp2.2_core",
            ],
            "netcoreapp3.0": [
               "@system.memory//:netcoreapp3.0_core",
               "@system.runtime.compilerservices.unsafe//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@system.memory//:netcoreapp3.1_core",
               "@system.runtime.compilerservices.unsafe//:netcoreapp3.1_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Google.Protobuf.dll",
               "lib/netstandard2.0/Google.Protobuf.pdb",
               "lib/netstandard2.0/Google.Protobuf.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Google.Protobuf.dll",
               "lib/netstandard2.0/Google.Protobuf.pdb",
               "lib/netstandard2.0/Google.Protobuf.xml",
            ],
            "netcoreapp2.2": [
               "lib/netstandard2.0/Google.Protobuf.dll",
               "lib/netstandard2.0/Google.Protobuf.pdb",
               "lib/netstandard2.0/Google.Protobuf.xml",
            ],
            "netcoreapp3.0": [
               "lib/netstandard2.0/Google.Protobuf.dll",
               "lib/netstandard2.0/Google.Protobuf.pdb",
               "lib/netstandard2.0/Google.Protobuf.xml",
            ],
            "netcoreapp3.1": [
               "lib/netstandard2.0/Google.Protobuf.dll",
               "lib/netstandard2.0/Google.Protobuf.pdb",
               "lib/netstandard2.0/Google.Protobuf.xml",
            ],
            "net5.0": [
               "lib/net5.0/Google.Protobuf.dll",
               "lib/net5.0/Google.Protobuf.pdb",
               "lib/net5.0/Google.Protobuf.xml",
            ],
        },
    )
    nuget_package(
        name = "grpc.core.api",
        package = "grpc.core.api",
        version = "2.40.0",
        sha256 = "79246badf1942f3966341894e2f1a9447c4ab3a7bbfd94b2879b5789c8cd7925",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Grpc.Core.Api.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Grpc.Core.Api.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Grpc.Core.Api.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Grpc.Core.Api.dll",
            "netcoreapp3.1": "lib/netstandard2.0/Grpc.Core.Api.dll",
            "net5.0": "lib/netstandard2.0/Grpc.Core.Api.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
               "@system.memory//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
               "@system.memory//:netcoreapp2.1_core",
            ],
            "netcoreapp2.2": [
               "@system.memory//:netcoreapp2.2_core",
            ],
            "netcoreapp3.0": [
               "@system.memory//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@system.memory//:netcoreapp3.1_core",
            ],
            "net5.0": [
               "@system.memory//:net5.0_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Grpc.Core.Api.dll",
               "lib/netstandard2.0/Grpc.Core.Api.pdb",
               "lib/netstandard2.0/Grpc.Core.Api.xml",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Grpc.Core.Api.dll",
               "lib/netstandard2.0/Grpc.Core.Api.pdb",
               "lib/netstandard2.0/Grpc.Core.Api.xml",
            ],
            "netcoreapp2.2": [
               "lib/netstandard2.0/Grpc.Core.Api.dll",
               "lib/netstandard2.0/Grpc.Core.Api.pdb",
               "lib/netstandard2.0/Grpc.Core.Api.xml",
            ],
            "netcoreapp3.0": [
               "lib/netstandard2.0/Grpc.Core.Api.dll",
               "lib/netstandard2.0/Grpc.Core.Api.pdb",
               "lib/netstandard2.0/Grpc.Core.Api.xml",
            ],
            "netcoreapp3.1": [
               "lib/netstandard2.0/Grpc.Core.Api.dll",
               "lib/netstandard2.0/Grpc.Core.Api.pdb",
               "lib/netstandard2.0/Grpc.Core.Api.xml",
            ],
            "net5.0": [
               "lib/netstandard2.0/Grpc.Core.Api.dll",
               "lib/netstandard2.0/Grpc.Core.Api.pdb",
               "lib/netstandard2.0/Grpc.Core.Api.xml",
            ],
        },
    )
    nuget_package(
        name = "grpc.core",
        package = "grpc.core",
        version = "2.40.0",
        sha256 = "b3d74d4d24e4bea1bf4be48849cf4c8ec5da51cf45d8f4c05338a5f76fa0a80e",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Grpc.Core.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Grpc.Core.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Grpc.Core.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Grpc.Core.dll",
            "netcoreapp3.1": "lib/netstandard2.0/Grpc.Core.dll",
            "net5.0": "lib/netstandard2.0/Grpc.Core.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
               "@grpc.core.api//:netcoreapp2.0_core",
               "@system.memory//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
               "@grpc.core.api//:netcoreapp2.1_core",
               "@system.memory//:netcoreapp2.1_core",
            ],
            "netcoreapp2.2": [
               "@grpc.core.api//:netcoreapp2.2_core",
               "@system.memory//:netcoreapp2.2_core",
            ],
            "netcoreapp3.0": [
               "@grpc.core.api//:netcoreapp3.0_core",
               "@system.memory//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@grpc.core.api//:netcoreapp3.1_core",
               "@system.memory//:netcoreapp3.1_core",
            ],
            "net5.0": [
               "@grpc.core.api//:net5.0_core",
               "@system.memory//:net5.0_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Grpc.Core.dll",
               "lib/netstandard2.0/Grpc.Core.pdb",
               "lib/netstandard2.0/Grpc.Core.xml",

                # Patched in by regenerate_packages.sh
                # Can't use select() here, so must just specify all
                "runtimes/win-x64/native/grpc_csharp_ext.x64.dll",
                "runtimes/win-x86/native/grpc_csharp_ext.x86.dll",
               "runtimes/linux-arm64/native/libgrpc_csharp_ext.arm64.so",
               "runtimes/linux-x64/native/libgrpc_csharp_ext.x64.so",
               "runtimes/osx-x64/native/libgrpc_csharp_ext.x64.dylib",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Grpc.Core.dll",
               "lib/netstandard2.0/Grpc.Core.pdb",
               "lib/netstandard2.0/Grpc.Core.xml",

                # Patched in by regenerate_packages.sh
                # Can't use select() here, so must just specify all
                "runtimes/win-x64/native/grpc_csharp_ext.x64.dll",
                "runtimes/win-x86/native/grpc_csharp_ext.x86.dll",
               "runtimes/linux-arm64/native/libgrpc_csharp_ext.arm64.so",
               "runtimes/linux-x64/native/libgrpc_csharp_ext.x64.so",
               "runtimes/osx-x64/native/libgrpc_csharp_ext.x64.dylib",
            ],
            "netcoreapp2.2": [
               "lib/netstandard2.0/Grpc.Core.dll",
               "lib/netstandard2.0/Grpc.Core.pdb",
               "lib/netstandard2.0/Grpc.Core.xml",

                # Patched in by regenerate_packages.sh
                # Can't use select() here, so must just specify all
                "runtimes/win-x64/native/grpc_csharp_ext.x64.dll",
                "runtimes/win-x86/native/grpc_csharp_ext.x86.dll",
               "runtimes/linux-arm64/native/libgrpc_csharp_ext.arm64.so",
               "runtimes/linux-x64/native/libgrpc_csharp_ext.x64.so",
               "runtimes/osx-x64/native/libgrpc_csharp_ext.x64.dylib",
            ],
            "netcoreapp3.0": [
               "lib/netstandard2.0/Grpc.Core.dll",
               "lib/netstandard2.0/Grpc.Core.pdb",
               "lib/netstandard2.0/Grpc.Core.xml",

                # Patched in by regenerate_packages.sh
                # Can't use select() here, so must just specify all
                "runtimes/win-x64/native/grpc_csharp_ext.x64.dll",
                "runtimes/win-x86/native/grpc_csharp_ext.x86.dll",
               "runtimes/linux-arm64/native/libgrpc_csharp_ext.arm64.so",
               "runtimes/linux-x64/native/libgrpc_csharp_ext.x64.so",
               "runtimes/osx-x64/native/libgrpc_csharp_ext.x64.dylib",
            ],
            "netcoreapp3.1": [
               "lib/netstandard2.0/Grpc.Core.dll",
               "lib/netstandard2.0/Grpc.Core.pdb",
               "lib/netstandard2.0/Grpc.Core.xml",

                # Patched in by regenerate_packages.sh
                # Can't use select() here, so must just specify all
                "runtimes/win-x64/native/grpc_csharp_ext.x64.dll",
                "runtimes/win-x86/native/grpc_csharp_ext.x86.dll",
               "runtimes/linux-arm64/native/libgrpc_csharp_ext.arm64.so",
               "runtimes/linux-x64/native/libgrpc_csharp_ext.x64.so",
               "runtimes/osx-x64/native/libgrpc_csharp_ext.x64.dylib",
            ],
            "net5.0": [
               "lib/netstandard2.0/Grpc.Core.dll",
               "lib/netstandard2.0/Grpc.Core.pdb",
               "lib/netstandard2.0/Grpc.Core.xml",

                # Patched in by regenerate_packages.sh
                # Can't use select() here, so must just specify all
                "runtimes/win-x64/native/grpc_csharp_ext.x64.dll",
                "runtimes/win-x86/native/grpc_csharp_ext.x86.dll",
               "runtimes/linux-arm64/native/libgrpc_csharp_ext.arm64.so",
               "runtimes/linux-x64/native/libgrpc_csharp_ext.x64.so",
               "runtimes/osx-x64/native/libgrpc_csharp_ext.x64.dylib",
            ],
        },
    )
    nuget_package(
        name = "grpc",
        package = "grpc",
        version = "2.40.0",
        sha256 = "931cf1271355b8ed3ce8a35aa1feb312b62398a4f0aa2e54767318b0adfda498",
        core_deps = {
            "netcoreapp2.0": [
               "@grpc.core//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
               "@grpc.core//:netcoreapp2.1_core",
            ],
            "netcoreapp2.2": [
               "@grpc.core//:netcoreapp2.2_core",
            ],
            "netcoreapp3.0": [
               "@grpc.core//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@grpc.core//:netcoreapp3.1_core",
            ],
            "net5.0": [
               "@grpc.core//:net5.0_core",
            ],
        },
    )
    nuget_package(
        name = "fsharp.core",
        package = "fsharp.core",
        version = "5.0.1",
        sha256 = "58f932b639c7953871cd894fbe6a4808c7d1fb800d4e258d1a3100e8ba007010",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
            "netcoreapp2.1": "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
            "netcoreapp2.2": "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
            "netcoreapp3.0": "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
            "netcoreapp3.1": "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
            "net5.0": "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
               "lib/netstandard2.0/de/FSharp.Core.resources.dll",
               "lib/netstandard2.0/es/FSharp.Core.resources.dll",
               "lib/netstandard2.0/fr/FSharp.Core.resources.dll",
               "lib/netstandard2.0/FSharp.Core.dll",
               "lib/netstandard2.0/FSharp.Core.xml",
               "lib/netstandard2.0/it/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ja/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ko/FSharp.Core.resources.dll",
               "lib/netstandard2.0/pl/FSharp.Core.resources.dll",
               "lib/netstandard2.0/pt-BR/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ru/FSharp.Core.resources.dll",
               "lib/netstandard2.0/tr/FSharp.Core.resources.dll",
               "lib/netstandard2.0/zh-Hans/FSharp.Core.resources.dll",
               "lib/netstandard2.0/zh-Hant/FSharp.Core.resources.dll",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
               "lib/netstandard2.0/de/FSharp.Core.resources.dll",
               "lib/netstandard2.0/es/FSharp.Core.resources.dll",
               "lib/netstandard2.0/fr/FSharp.Core.resources.dll",
               "lib/netstandard2.0/FSharp.Core.dll",
               "lib/netstandard2.0/FSharp.Core.xml",
               "lib/netstandard2.0/it/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ja/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ko/FSharp.Core.resources.dll",
               "lib/netstandard2.0/pl/FSharp.Core.resources.dll",
               "lib/netstandard2.0/pt-BR/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ru/FSharp.Core.resources.dll",
               "lib/netstandard2.0/tr/FSharp.Core.resources.dll",
               "lib/netstandard2.0/zh-Hans/FSharp.Core.resources.dll",
               "lib/netstandard2.0/zh-Hant/FSharp.Core.resources.dll",
            ],
            "netcoreapp2.2": [
               "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
               "lib/netstandard2.0/de/FSharp.Core.resources.dll",
               "lib/netstandard2.0/es/FSharp.Core.resources.dll",
               "lib/netstandard2.0/fr/FSharp.Core.resources.dll",
               "lib/netstandard2.0/FSharp.Core.dll",
               "lib/netstandard2.0/FSharp.Core.xml",
               "lib/netstandard2.0/it/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ja/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ko/FSharp.Core.resources.dll",
               "lib/netstandard2.0/pl/FSharp.Core.resources.dll",
               "lib/netstandard2.0/pt-BR/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ru/FSharp.Core.resources.dll",
               "lib/netstandard2.0/tr/FSharp.Core.resources.dll",
               "lib/netstandard2.0/zh-Hans/FSharp.Core.resources.dll",
               "lib/netstandard2.0/zh-Hant/FSharp.Core.resources.dll",
            ],
            "netcoreapp3.0": [
               "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
               "lib/netstandard2.0/de/FSharp.Core.resources.dll",
               "lib/netstandard2.0/es/FSharp.Core.resources.dll",
               "lib/netstandard2.0/fr/FSharp.Core.resources.dll",
               "lib/netstandard2.0/FSharp.Core.dll",
               "lib/netstandard2.0/FSharp.Core.xml",
               "lib/netstandard2.0/it/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ja/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ko/FSharp.Core.resources.dll",
               "lib/netstandard2.0/pl/FSharp.Core.resources.dll",
               "lib/netstandard2.0/pt-BR/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ru/FSharp.Core.resources.dll",
               "lib/netstandard2.0/tr/FSharp.Core.resources.dll",
               "lib/netstandard2.0/zh-Hans/FSharp.Core.resources.dll",
               "lib/netstandard2.0/zh-Hant/FSharp.Core.resources.dll",
            ],
            "netcoreapp3.1": [
               "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
               "lib/netstandard2.0/de/FSharp.Core.resources.dll",
               "lib/netstandard2.0/es/FSharp.Core.resources.dll",
               "lib/netstandard2.0/fr/FSharp.Core.resources.dll",
               "lib/netstandard2.0/FSharp.Core.dll",
               "lib/netstandard2.0/FSharp.Core.xml",
               "lib/netstandard2.0/it/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ja/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ko/FSharp.Core.resources.dll",
               "lib/netstandard2.0/pl/FSharp.Core.resources.dll",
               "lib/netstandard2.0/pt-BR/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ru/FSharp.Core.resources.dll",
               "lib/netstandard2.0/tr/FSharp.Core.resources.dll",
               "lib/netstandard2.0/zh-Hans/FSharp.Core.resources.dll",
               "lib/netstandard2.0/zh-Hant/FSharp.Core.resources.dll",
            ],
            "net5.0": [
               "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
               "lib/netstandard2.0/de/FSharp.Core.resources.dll",
               "lib/netstandard2.0/es/FSharp.Core.resources.dll",
               "lib/netstandard2.0/fr/FSharp.Core.resources.dll",
               "lib/netstandard2.0/FSharp.Core.dll",
               "lib/netstandard2.0/FSharp.Core.xml",
               "lib/netstandard2.0/it/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ja/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ko/FSharp.Core.resources.dll",
               "lib/netstandard2.0/pl/FSharp.Core.resources.dll",
               "lib/netstandard2.0/pt-BR/FSharp.Core.resources.dll",
               "lib/netstandard2.0/ru/FSharp.Core.resources.dll",
               "lib/netstandard2.0/tr/FSharp.Core.resources.dll",
               "lib/netstandard2.0/zh-Hans/FSharp.Core.resources.dll",
               "lib/netstandard2.0/zh-Hant/FSharp.Core.resources.dll",
            ],
        },
    )
    nuget_package(
        name = "protobuf.fsharp",
        package = "protobuf.fsharp",
        version = "0.1.1",
        sha256 = "cdb3f01a7ab2de3c2012b355a4f89ebdd8a9b4a8bf58eed23e3d2e80d95d8829",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/Protobuf.FSharp.dll",
            "netcoreapp2.1": "lib/netstandard2.0/Protobuf.FSharp.dll",
            "netcoreapp2.2": "lib/netstandard2.0/Protobuf.FSharp.dll",
            "netcoreapp3.0": "lib/netstandard2.0/Protobuf.FSharp.dll",
            "netcoreapp3.1": "lib/netstandard2.0/Protobuf.FSharp.dll",
            "net5.0": "lib/netstandard2.0/Protobuf.FSharp.dll",
        },
        core_deps = {
            "netcoreapp2.0": [
               "@fsharp.core//:netcoreapp2.0_core",
               "@google.protobuf//:netcoreapp2.0_core",
            ],
            "netcoreapp2.1": [
               "@fsharp.core//:netcoreapp2.1_core",
               "@google.protobuf//:netcoreapp2.1_core",
            ],
            "netcoreapp2.2": [
               "@fsharp.core//:netcoreapp2.2_core",
               "@google.protobuf//:netcoreapp2.2_core",
            ],
            "netcoreapp3.0": [
               "@fsharp.core//:netcoreapp3.0_core",
               "@google.protobuf//:netcoreapp3.0_core",
            ],
            "netcoreapp3.1": [
               "@fsharp.core//:netcoreapp3.1_core",
               "@google.protobuf//:netcoreapp3.1_core",
            ],
            "net5.0": [
               "@fsharp.core//:net5.0_core",
               "@google.protobuf//:net5.0_core",
            ],
        },
        core_files = {
            "netcoreapp2.0": [
               "lib/netstandard2.0/Protobuf.FSharp.dll",
            ],
            "netcoreapp2.1": [
               "lib/netstandard2.0/Protobuf.FSharp.dll",
            ],
            "netcoreapp2.2": [
               "lib/netstandard2.0/Protobuf.FSharp.dll",
            ],
            "netcoreapp3.0": [
               "lib/netstandard2.0/Protobuf.FSharp.dll",
            ],
            "netcoreapp3.1": [
               "lib/netstandard2.0/Protobuf.FSharp.dll",
            ],
            "net5.0": [
               "lib/netstandard2.0/Protobuf.FSharp.dll",
            ],
        },
    )
    ### End of generated by the tool
    dotnet_nuget_new(
        name = "protoc-gen-fsharp",
        build_file_content = """
load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "core_import_binary", "core_import_library")
core_import_library(
    name = "Protobuf.FSharp.dll",
    src = select(
        {
            "@io_bazel_rules_dotnet//dotnet/toolchain:2.1.200_config": "tools/netcoreapp2.1/any/Protobuf.FSharp.dll",
            "@io_bazel_rules_dotnet//dotnet/toolchain:2.1.502_config": "tools/netcoreapp2.1/any/Protobuf.FSharp.dll",
            "@io_bazel_rules_dotnet//dotnet/toolchain:2.1.503_config": "tools/netcoreapp2.1/any/Protobuf.FSharp.dll",
            "@io_bazel_rules_dotnet//dotnet/toolchain:2.2.101_config": "tools/netcoreapp2.1/any/Protobuf.FSharp.dll",
            "@io_bazel_rules_dotnet//dotnet/toolchain:2.2.402_config": "tools/netcoreapp2.1/any/Protobuf.FSharp.dll",
            "@io_bazel_rules_dotnet//dotnet/toolchain:3.0.100_config": "tools/netcoreapp2.1/any/Protobuf.FSharp.dll",
            "@io_bazel_rules_dotnet//dotnet/toolchain:3.1.100_config": "tools/netcoreapp3.1/any/Protobuf.FSharp.dll",
            "@io_bazel_rules_dotnet//dotnet/toolchain:3.1.407_config": "tools/netcoreapp3.1/any/Protobuf.FSharp.dll",
            "@io_bazel_rules_dotnet//dotnet/toolchain:5.0.201_config": "tools/net5.0/any/Protobuf.FSharp.dll",
        },
    ),
    version = "0.1.1",
    deps = [
        "@fsharp.core//:lib",
        "@google.protobuf//:lib",
    ],
)

core_import_binary(
    name = "bin",
    src = select(
        {
            "@io_bazel_rules_dotnet//dotnet/toolchain:2.1.200_config": "tools/netcoreapp2.1/any/FSharp.GrpcCodeGenerator.dll",
            "@io_bazel_rules_dotnet//dotnet/toolchain:2.1.502_config": "tools/netcoreapp2.1/any/FSharp.GrpcCodeGenerator.dll",
            "@io_bazel_rules_dotnet//dotnet/toolchain:2.1.503_config": "tools/netcoreapp2.1/any/FSharp.GrpcCodeGenerator.dll",
            "@io_bazel_rules_dotnet//dotnet/toolchain:2.2.101_config": "tools/netcoreapp2.1/any/FSharp.GrpcCodeGenerator.dll",
            "@io_bazel_rules_dotnet//dotnet/toolchain:2.2.402_config": "tools/netcoreapp2.1/any/FSharp.GrpcCodeGenerator.dll",
            "@io_bazel_rules_dotnet//dotnet/toolchain:3.0.100_config": "tools/netcoreapp2.1/any/FSharp.GrpcCodeGenerator.dll",
            "@io_bazel_rules_dotnet//dotnet/toolchain:3.1.100_config": "tools/netcoreapp3.1/any/FSharp.GrpcCodeGenerator.dll",
            "@io_bazel_rules_dotnet//dotnet/toolchain:3.1.407_config": "tools/netcoreapp3.1/any/FSharp.GrpcCodeGenerator.dll",
            "@io_bazel_rules_dotnet//dotnet/toolchain:5.0.201_config": "tools/net5.0/any/FSharp.GrpcCodeGenerator.dll",
        },
    ),
    deps = [":Protobuf.FSharp.dll"],
    version = "0.1.3",
    visibility = ["//visibility:public"],
)
    """,
        package = "grpc-fsharp",
        version = "0.1.3",
        sha256 = "f1612d2d3ca0715087a87050cb7a3ebb98ff7c9294bb65afab19f7c648d1bed1",
    )
