local_repository(
    name = "rules_proto_grpc",
    path = "../../../../../",
)

load("@rules_proto_grpc//github.com/gogo/protobuf:repositories.bzl", rules_proto_grpc_gogo_repos="gogo_repos")

rules_proto_grpc_gogo_repos()

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains()
