local_repository(
    name = "rules_proto_grpc",
    path = "../../../",
)

load("@rules_proto_grpc//java:repositories.bzl", "java_deps")

java_deps()

load("@io_grpc_grpc_java//:repositories.bzl", "com_google_guava")

com_google_guava()
