local_repository(
    name = "rules_proto_grpc",
    path = "../../../../../",
)

load("@rules_proto_grpc//github.com/grpc/grpc-web:deps.bzl", "grpc_web_deps")

grpc_web_deps()

load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")

closure_repositories(
    omit_com_google_protobuf = True,
)
