local_repository(
    name = "rules_proto_grpc",
    path = "../../",
)

load("@rules_proto_grpc//go:repositories.bzl", "go_repos")

go_repos()

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains()