name: Other
description: File a feature request or any other issue
type: Task
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue, feature request or anything else.
    validations:
      required: true
