local_repository(
    name = "rules_proto_grpc",
    path = "../../../",
)

load("@rules_proto_grpc//python:repositories.bzl", "python_deps")

python_deps()

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()
