local_repository(
    name = "rules_proto_grpc",
    path = "../../",
)

load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_toolchains")
rules_proto_grpc_toolchains()

load("@rules_proto_grpc//python:repositories.bzl", "python_repos")
python_repos()
