local_repository(
    name = "rules_proto_grpc",
    path = "../../../../../",
)

load("@rules_proto_grpc//github.com/stackb/grpc.js:repositories.bzl", rules_proto_grpc_grpcjs_repos="grpcjs_repos")

rules_proto_grpc_grpcjs_repos()
