local_repository(
    name = "rules_proto_grpc",
    path = "../../",
)

load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_toolchains", "rules_proto_grpc_dependencies")
rules_proto_grpc_toolchains()
rules_proto_grpc_dependencies()

load("@rules_proto_grpc//objc:repositories.bzl", "objc_repos")
objc_repos()
