[package]
name = "compile_with_bazel"
version = "0.0.0"

# Mandatory (or Cargo tooling is unhappy)
[lib]
path = "lib.rs"

[dependencies]
futures = "=0.3.17"
grpc = "=0.8.3"
grpc-compiler = "=0.8.3"
grpc-protobuf = "=0.8.3"
protobuf = { version = "=2.18.2", features = ["with-bytes"] }
protobuf-codegen = "=2.18.2"

# For routeguide example
json = "=0.12.4"
rand = "=0.6.5"

[package.metadata.raze]
genmode = "Remote"
workspace_path = "//rust/raze"
output_buildfile_suffix = "BUILD.bazel"
package_aliases_dir = "."
default_gen_buildrs = true
rust_rules_workspace_name = "rules_rust"


# Plugins
[package.metadata.raze.crates.grpc-compiler.'*']
extra_aliased_targets = ["cargo_bin_protoc_gen_rust_grpc"]

[package.metadata.raze.crates.protobuf-codegen.'*']
extra_aliased_targets = ["cargo_bin_protoc_gen_rust"]
